// Generated by gencpp from file assignment_2_2022/Service1Request.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_SERVICE1REQUEST_H
#define ASSIGNMENT_2_2022_MESSAGE_SERVICE1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2022
{
template <class ContainerAllocator>
struct Service1Request_
{
  typedef Service1Request_<ContainerAllocator> Type;

  Service1Request_()
    : call(0)  {
    }
  Service1Request_(const ContainerAllocator& _alloc)
    : call(0)  {
  (void)_alloc;
    }



   typedef int16_t _call_type;
  _call_type call;





  typedef boost::shared_ptr< ::assignment_2_2022::Service1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2022::Service1Request_<ContainerAllocator> const> ConstPtr;

}; // struct Service1Request_

typedef ::assignment_2_2022::Service1Request_<std::allocator<void> > Service1Request;

typedef boost::shared_ptr< ::assignment_2_2022::Service1Request > Service1RequestPtr;
typedef boost::shared_ptr< ::assignment_2_2022::Service1Request const> Service1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2022::Service1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2022::Service1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2022::Service1Request_<ContainerAllocator1> & lhs, const ::assignment_2_2022::Service1Request_<ContainerAllocator2> & rhs)
{
  return lhs.call == rhs.call;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2022::Service1Request_<ContainerAllocator1> & lhs, const ::assignment_2_2022::Service1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::Service1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::Service1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::Service1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "336b9dddfa0a2e29c717dc025c1aa0e5";
  }

  static const char* value(const ::assignment_2_2022::Service1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x336b9dddfa0a2e29ULL;
  static const uint64_t static_value2 = 0xc717dc025c1aa0e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2022/Service1Request";
  }

  static const char* value(const ::assignment_2_2022::Service1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 call\n"
;
  }

  static const char* value(const ::assignment_2_2022::Service1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.call);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Service1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2022::Service1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2022::Service1Request_<ContainerAllocator>& v)
  {
    s << indent << "call: ";
    Printer<int16_t>::stream(s, indent + "  ", v.call);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_SERVICE1REQUEST_H
