// Generated by gencpp from file assignment_2_2022/Service1.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_SERVICE1_H
#define ASSIGNMENT_2_2022_MESSAGE_SERVICE1_H

#include <ros/service_traits.h>


#include <assignment_2_2022/Service1Request.h>
#include <assignment_2_2022/Service1Response.h>


namespace assignment_2_2022
{

struct Service1
{

typedef Service1Request Request;
typedef Service1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service1
} // namespace assignment_2_2022


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2022::Service1 > {
  static const char* value()
  {
    return "e5d53304d667c7bb1c841768acfb5d86";
  }

  static const char* value(const ::assignment_2_2022::Service1&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2022::Service1 > {
  static const char* value()
  {
    return "assignment_2_2022/Service1";
  }

  static const char* value(const ::assignment_2_2022::Service1&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2022::Service1Request> should match
// service_traits::MD5Sum< ::assignment_2_2022::Service1 >
template<>
struct MD5Sum< ::assignment_2_2022::Service1Request>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::Service1 >::value();
  }
  static const char* value(const ::assignment_2_2022::Service1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::Service1Request> should match
// service_traits::DataType< ::assignment_2_2022::Service1 >
template<>
struct DataType< ::assignment_2_2022::Service1Request>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::Service1 >::value();
  }
  static const char* value(const ::assignment_2_2022::Service1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2022::Service1Response> should match
// service_traits::MD5Sum< ::assignment_2_2022::Service1 >
template<>
struct MD5Sum< ::assignment_2_2022::Service1Response>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::Service1 >::value();
  }
  static const char* value(const ::assignment_2_2022::Service1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::Service1Response> should match
// service_traits::DataType< ::assignment_2_2022::Service1 >
template<>
struct DataType< ::assignment_2_2022::Service1Response>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::Service1 >::value();
  }
  static const char* value(const ::assignment_2_2022::Service1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_SERVICE1_H
